#Output files
EXECUTABLE=stm32_executable.elf
BIN_IMAGE=stm32_bin_image.bin

#======================================================================#
#Cross Compiler
CC=arm-none-eabi-gcc
OBJCOPY=arm-none-eabi-objcopy
#======================================================================#

#CMSIS libraries include
CFLAGS+=-I./Libraries/CMSIS
#Stm32 libraries include
ST_LIB=./Libraries/STM32F4xx_StdPeriph_Driver
